services:
  database:
    image: mongo:4.1.13
    container_name: mongodb
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - net_A

  backend:
    container_name: server
    image: test
    ports:
      - "3003:3003"
    depends_on:
      - database
    networks:
      - net_A

networks:
  net_A:
    driver: bridge

volumes:
  mongo_data:
