services:
  database:
    image: mongo:4.1.13
    container_name: db
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - net_A

  backend:
    container_name: server
    ports:
      - "3003:3000"
    depends_on:
      - database
    build: .      
    networks:
      - net_A

networks:
  net_A:
    external: false

volumes:
  mongo_data:
