#!/bin/bash

echo "FROM node:14

EXPOSE 8080

WORKDIR /app

COPY package.json .

RUN npm install

COPY server.js .

CMD node server.js
" > Dockerfile

echo "{
  \"version\": \"1.0.0\",
  \"dependencies\": {
    \"express\": \"4.18.3\"
  }
}
" > package.json

echo "const express = require('express');
const app = express();

app.get('/', (req, res) => {
  res.send('Hello World!');
});

app.listen(8080, () => {
  console.log('Server is running on port ' + 8080);
});
" > server.js

docker build -t node .

docker run -p 8080:8080 node
