services:
  db:
    build: ./db
    restart: always
    shm_size: 128mb
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass example
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  web:
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    command: node src/server.js

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - web
    
volumes:
  db-data:
  redis-data: